import { prisma } from '../../config/prisma.js';
import { ApiError } from '../../utils/apiError.js';
import { exportToExcel, exportToPDFTable } from '../../utils/export.utility.js';

export const getSalesReport = async (tenantId, filters = {}) => {
  const {
    startDate,
    endDate,
    customerId,
    employeeId,
    paymentMethod,
    paymentStatus,
    categoryId,
    subCategoryId,
    productId,
    search
  } = filters;

  const where = { tenantId };

  if (startDate || endDate) {
    where.createdAt = {};
    if (startDate) where.createdAt.gte = new Date(startDate);
    if (endDate) where.createdAt.lte = new Date(endDate);
  }

  if (customerId) where.customerId = customerId;
  if (employeeId) where.generatedByUserId = employeeId;
  if (paymentMethod) where.paymentMethod = paymentMethod;
  if (paymentStatus) where.status = paymentStatus;
  if (search) {
    where.invoiceNumber = { contains: search, mode: 'insensitive' };
  }

  if (categoryId || subCategoryId || productId) {
    where.items = {
      some: {
        ...(productId && { productId }),
        ...(categoryId || subCategoryId ? {
          product: {
            ...(categoryId && { categoryId }),
            ...(subCategoryId && { subCategoryId })
          }
        } : {})
      }
    };
  }

  const bills = await prisma.bill.findMany({
    where,
    include: {
      customer: true,
      generatedBy: { select: { id: true, name: true, role: true } },
      items: { include: { product: true } }
    },
    orderBy: { createdAt: 'desc' }
  });

  // Calculate Aggregations
  let totalInvoices = bills.length;
  let totalProductsSold = 0;
  let totalSales = 0;
  let totalDiscount = 0;
  let totalTax = 0;
  let totalPaidAmount = 0;
  let totalUnpaidAmount = 0;

  for (const b of bills) {
    totalSales += b.grandTotal;
    totalDiscount += b.discountAmount;
    totalTax += b.totalTaxAmount;
    totalPaidAmount += b.paidAmount;
    totalUnpaidAmount += b.dueAmount;

    for (const item of b.items) {
      totalProductsSold += (item.quantity - item.returnedQuantity);
    }
  }

  const netSales = Math.max(0, totalSales - totalDiscount);

  return {
    summary: {
      totalInvoices,
      totalProductsSold,
      totalSales,
      totalDiscount,
      totalTax,
      totalPaidAmount,
      totalUnpaidAmount,
      netSales
    },
    bills
  };
};

export const generateSalesReportPDF = async (tenantId, filters, res) => {
  const reportData = await getSalesReport(tenantId, filters);
  const tenant = await prisma.tenant.findUnique({ where: { id: tenantId } });

  const columns = [
    { header: 'Invoice Number', key: 'invoiceNumber' },
    { header: 'Customer Name', key: 'customerName' },
    { header: 'Date', key: 'date' },
    { header: 'Status', key: 'status' },
    { header: 'Grand Total (₹)', key: 'grandTotal' }
  ];

  const data = reportData.bills.map(b => ({
    invoiceNumber: b.invoiceNumber,
    customerName: b.customer ? b.customer.name : 'N/A',
    date: b.createdAt ? new Date(b.createdAt).toLocaleDateString() : '',
    status: b.status,
    grandTotal: b.grandTotal
  }));

  return await exportToPDFTable(res, {
    filename: 'sales_summary_report',
    title: 'Filtered Sales Summary Report',
    businessName: tenant ? tenant.businessName : 'SoftFYR Billing SaaS Platform',
    columns,
    data,
    summary: reportData.summary
  });
};

export const generateSalesReportExcel = async (tenantId, filters, res) => {
  const reportData = await getSalesReport(tenantId, filters);

  const columns = [
    { header: 'Invoice Number', key: 'invoiceNumber', width: 18 },
    { header: 'Invoice Date', key: 'createdAt', width: 14 },
    { header: 'Customer Name', key: 'customerName', width: 22 },
    { header: 'Payment Method', key: 'paymentMethod', width: 15 },
    { header: 'Payment Status', key: 'status', width: 15 },
    { header: 'Subtotal (₹)', key: 'subtotal', width: 14 },
    { header: 'Tax (₹)', key: 'totalTaxAmount', width: 14 },
    { header: 'Discount (₹)', key: 'discountAmount', width: 14 },
    { header: 'Grand Total (₹)', key: 'grandTotal', width: 15 },
    { header: 'Paid Amount (₹)', key: 'paidAmount', width: 15 },
    { header: 'Generated By', key: 'generatedBy', width: 18 }
  ];

  const data = reportData.bills.map(b => ({
    invoiceNumber: b.invoiceNumber,
    createdAt: new Date(b.createdAt).toLocaleDateString(),
    customerName: b.customer ? b.customer.name : 'N/A',
    paymentMethod: b.paymentMethod,
    status: b.status,
    subtotal: b.subtotal,
    totalTaxAmount: b.totalTaxAmount,
    discountAmount: b.discountAmount,
    grandTotal: b.grandTotal,
    paidAmount: b.paidAmount,
    generatedBy: b.generatedBy ? b.generatedBy.name : 'System'
  }));

  const summaryRows = [
    {
      invoiceNumber: 'TOTAL SUMMARY',
      grandTotal: reportData.summary.totalSales,
      paidAmount: reportData.summary.totalPaidAmount
    }
  ];

  return await exportToExcel(res, {
    filename: 'sales_report',
    sheetName: 'Sales Report',
    columns,
    data,
    summaryRows
  });
};
